// @ts-nocheck
import { getSql, checkAuth, cors } from "./_lib/db.js";

export const config = {
  api: { bodyParser: { sizeLimit: "4mb" } },
};

const GEMINI_MODEL = "gemini-2.5-flash";

async function generateBlogWithAI(topic: string, category: string) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY not configured");

  const prompt = `You are an expert digital marketing blog writer for "Adsrahu", a premium real estate lead generation and performance marketing agency based in India.

Write a complete, professional, SEO-optimized blog post on the following topic:
Topic: "${topic}"
Category: "${category}"

The blog should be written for real estate developers, builders, and business owners who want to grow using digital marketing.

Return your response as valid JSON with these exact keys:
{
  "title": "An SEO-friendly, compelling blog title (50-70 chars)",
  "slug": "url-friendly-slug-with-hyphens",
  "excerpt": "A compelling 1-2 sentence summary for the blog card (under 160 chars)",
  "content": "The full blog body in Markdown format. Include:\n- An engaging introduction\n- 3-5 sections with ## headings\n- Practical tips, statistics, and actionable advice\n- A conclusion with a CTA to contact Adsrahu\n- Aim for 800-1200 words",
  "imageQuery": "A 2-3 word Unsplash search query for a relevant, professional cover image (e.g. 'digital marketing', 'real estate office', 'business analytics')"
}

IMPORTANT: Return ONLY the JSON object. No markdown code fences, no extra text.`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey,
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.8,
          maxOutputTokens: 4096,
          responseMimeType: "application/json",
        },
      }),
    }
  );

  if (!response.ok) {
    const errBody = await response.text();
    throw new Error(`Gemini API error: ${response.status} - ${errBody}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("No content generated by Gemini");

  // Parse the JSON response
  let parsed;
  try {
    // Try direct parse first
    parsed = JSON.parse(text);
  } catch (e1) {
    try {
      // Try extracting JSON from markdown code fences
      const match = text.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (match) {
        parsed = JSON.parse(match[1].trim());
      } else {
        // Fallback: try finding the first { and last }
        const firstBrace = text.indexOf('{');
        const lastBrace = text.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
          parsed = JSON.parse(text.substring(firstBrace, lastBrace + 1));
        } else {
          throw new Error("No JSON structure found");
        }
      }
    } catch (e2) {
      throw new Error("Failed to parse Gemini response as JSON. Snippet: " + text.substring(0, 150));
    }
  }

  // Build a relevant Unsplash cover image URL
  const query = encodeURIComponent(parsed.imageQuery || category || "digital marketing");
  const imageUrl = `https://images.unsplash.com/photo-${Date.now()}?w=1200&h=630&fit=crop&q=80`;
  // Use Unsplash source API for a random relevant image
  const unsplashUrl = `https://source.unsplash.com/1200x630/?${query}`;

  return {
    title: parsed.title,
    slug: parsed.slug,
    category,
    excerpt: parsed.excerpt,
    content: parsed.content,
    imageUrl: unsplashUrl,
  };
}

export default async function handler(req: any, res: any) {
  cors(res);
  if (req.method === "OPTIONS") { res.status(200).end(); return; }

  const sql = getSql();

  if (req.method === "GET") {
    const onlyPublished = req.query?.published === "true";
    const rows = onlyPublished
      ? await sql`SELECT * FROM blog_posts WHERE published = true ORDER BY created_at DESC`
      : await sql`SELECT * FROM blog_posts ORDER BY created_at DESC`;
    res.status(200).json(rows.map(toCamel));
    return;
  }

  if (req.method === "POST") {
    if (!checkAuth(req.headers["authorization"])) { res.status(401).json({ error: "Unauthorized" }); return; }

    // AI Blog Generation
    if (req.query?.action === "generate") {
      let b = req.body ?? {};
      if (typeof b === "string") { try { b = JSON.parse(b); } catch (e) {} }
      const topic = b.topic || b.title || "";
      const category = b.category || "Real Estate Lead Generation";
      if (!topic) { res.status(400).json({ error: "topic is required" }); return; }
      try {
        const generated = await generateBlogWithAI(topic, category);
        res.status(200).json(generated);
      } catch (err) {
        res.status(500).json({ error: err.message || "AI generation failed" });
      }
      return;
    }

    // Normal blog creation
    let b = req.body ?? {};
    if (typeof b === "string") {
      try { b = JSON.parse(b); } catch (e) {}
    }
    if (!b.title || !b.slug) { res.status(400).json({ error: "title and slug required" }); return; }
    const rows = await sql`
      INSERT INTO blog_posts (title, slug, category, excerpt, content, published, image_url)
      VALUES (${b.title}, ${b.slug}, ${b.category ?? "General"}, ${b.excerpt ?? ""}, ${b.content ?? ""}, ${b.published ?? false}, ${b.imageUrl ?? null})
      RETURNING *`;
    res.status(201).json(toCamel(rows[0]));
    return;
  }

  res.status(405).json({ error: "Method not allowed" });
}

function toCamel(row: any) {
  return { id: row.id, title: row.title, slug: row.slug, category: row.category, excerpt: row.excerpt, content: row.content, published: row.published, createdAt: row.created_at, imageUrl: row.image_url };
}
